device:
  name: tangorpro
  build_id: AP1A.240505.004

platform:
  product_makefile: device/google/tangorpro/aosp_tangorpro.mk

includes:
  - common/gen7pixel.yml

filters:
  overlay_files:
    prefix:
      # DockSetup itself is not shipped
      - DockSetup__auto_generated_rro_
