filters:
  files:
    match:
      # APEX allowlist
      - product/etc/sysconfig/vendor-apex-allowlist.xml
      # Boot animation
      - product/media/bootanimation.zip
      - product/media/bootanimation-dark.zip
      # Fonts
      - product/etc/fonts_customization.xml
      # GMS Game service
      - product/etc/sysconfig/game_service.xml
      # Google stuff we dont want/need/cant use
      - product/etc/permissions/com.google.android.apps.diagnosticstool.xml
      - product/etc/permissions/com.google.android.apps.dreamliner.xml
      - product/etc/permissions/com.google.android.apps.mediashell.xml
      - product/etc/permissions/com.google.android.apps.nest.castauth.xml
      - product/etc/permissions/com.google.android.dialer.support.xml
      - product/etc/permissions/com.google.assistant.hubui.xml
      - product/etc/permissions/com.google.SSRestartDetector.xml
      - product/etc/permissions/privapp-permissions-google-p.xml
      - product/etc/permissions/split-permissions-google.xml
      - product/etc/sysconfig/GoogleCamera_6gb_or_more_ram.xml
      - product/etc/sysconfig/adaptivecharging.xml
      - product/etc/sysconfig/communal.xml
      - product/etc/sysconfig/dreamliner.xml
      - product/etc/sysconfig/game_overlay.xml
      - product/etc/sysconfig/google-hiddenapi-package-whitelist.xml
      - product/etc/sysconfig/google-staged-installer-whitelist.xml
      - product/etc/sysconfig/google.xml
      - product/etc/sysconfig/google_build.xml
      - product/etc/sysconfig/google_fi.xml
      - product/etc/sysconfig/kids_home_experience.xml
      - product/etc/sysconfig/nexus.xml
      - product/etc/sysconfig/nga.xml
      - product/etc/sysconfig/pixel_2019_exclusive.xml
      - product/etc/sysconfig/pixel_docking_experience_2022.xml
      - product/etc/sysconfig/pixel_experience_2017.xml
      - product/etc/sysconfig/pixel_experience_2018.xml
      - product/etc/sysconfig/pixel_experience_2019.xml
      - product/etc/sysconfig/pixel_experience_2019_midyear.xml
      - product/etc/sysconfig/pixel_experience_2020.xml
      - product/etc/sysconfig/pixel_experience_2020_midyear.xml
      - product/etc/sysconfig/pixel_experience_2021.xml
      - product/etc/sysconfig/pixel_experience_2021_midyear.xml
      - product/etc/sysconfig/pixel_experience_2022.xml
      - product/etc/sysconfig/pixel_experience_2022_midyear.xml
      - product/etc/sysconfig/pixel_tablet_experience_2023.xml
      - product/etc/sysconfig/preinstalled-packages-product-pixel-2017-and-newer.xml
      - product/etc/sysconfig/quick_tap.xml
      - product/framework/com.google.android.dialer.support.jar
      - system/etc/permissions/privapp-permissions-google.xml
      - system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml
      - system_ext/etc/permissions/com.google.android.apps.nest.dockmanager.app.xml
      - system_ext/etc/permissions/privapp-permissions-google-se.xml
      - system_ext/framework/com.android.hotwordenrollment.common.util.jar
      - vendor/etc/default-permissions/default-permissions_talkback.xml
      - product/etc/sysconfig/google-install-constraints-package-allowlist.xml
      # Irrelevant OTA updater
      - system_ext/etc/init/init.sota.rc
      - system_ext/etc/permissions/com.google.android.factoryota.xml
      # Unused Face Unlock stuff
      - product/etc/permissions/android.hardware.biometrics.face.xml
      - vendor/bin/hw/android.hardware.biometrics.face-service.22.pixel
      - vendor/etc/faceauth_pipeline_input_pixel_22
      - vendor/etc/init/android.hardware.biometrics.face-service.22.pixel.rc
      - vendor/etc/init/init.faceauth.rc
      - vendor/firmware/faceauth_p22.app
      - vendor/lib64/com.google.face.debug-V1-ndk.so
      - vendor/lib64/com.google.face.debug-V2-ndk.so
      - vendor/lib64/libface_tuscany_sensor_trusty.so
      - vendor/lib64/libface_common_thread.so
      - vendor/lib64/libface_common_util.so
      - vendor/lib64/libface_common_camera.so
      - vendor/lib64/libface_hal_trusty_tuscany.so
      - vendor/lib64/libface_tuscany_trusty_debug_host.so
      - vendor/lib64/libface_common_capture.so
      - vendor/lib64/libface_common_log.so
      - vendor/lib64/libface_tuscany_cache_manager.so
      - vendor/lib64/libface_common_user.so
      - vendor/lib64/libface_common_trustzone.so
      - vendor/lib64/libface_common_perf.so
      - vendor/lib64/libface_common_fake_camera.so
      - vendor/lib64/libface_common_debug.so
      - vendor/lib64/libface_tuscany_cache_proto.so
      - vendor/lib64/libface_tuscany_proxy_util_trusty.so
      - vendor/lib64/libface_common_user_proto.so
      - vendor/lib64/libface_common_task.so
      - vendor/lib64/libface_common_frame.so
      - vendor/etc/vintf/manifest/android.hardware.biometrics.face-service.22.pixel.xml
      # Unused RadioConfigLib.jar
      - system_ext/etc/permissions/com.android.omadm.radioconfig.xml
      - system_ext/framework/RadioConfigLib.jar
      # Unused hardware info jar
      - product/etc/permissions/com.google.android.hardwareinfo.xml
      - product/framework/libhwinfo.jar
      # Unwanted OMA-DM and carrier trash
      - product/etc/default-permissions/default-permissions_diagnostictool.xml
      - product/etc/default-permissions/default-permissions_SmartDisplayPrebuilt.xml
      - product/etc/permissions/com.android.omadm.service.xml
      - product/etc/permissions/com.android.sdm.plugins.connmo.xml
      - product/etc/permissions/com.android.sdm.plugins.dcmo.xml
      - product/etc/permissions/com.android.sdm.plugins.diagmon.xml
      - product/etc/permissions/com.android.sdm.plugins.sprintdm.xml
      - product/etc/permissions/com.android.sdm.plugins.usccdm.xml
      - product/etc/permissions/com.customermobile.preload.vzw.xml
      - product/etc/permissions/com.google.android.odad.xml
      - product/etc/permissions/com.google.omadm.trigger.xml
      - product/etc/permissions/com.verizon.apn.xml
      - product/etc/permissions/com.verizon.services.xml
      - product/etc/sysconfig/allowlist_com.android.omadm.service.xml
      - system_ext/etc/permissions/com.verizon.llkagent.xml
      - system_ext/etc/permissions/obdm_permissions.xml
      - system_ext/etc/permissions/vzw_mvs_permissions.xml
      # odm useless
      - vendor/odm/etc/NOTICE.xml.gz
      - vendor/odm_dlkm/etc/build.prop
      - vendor/odm_dlkm/etc/NOTICE.xml.gz
      # ssrestart files
      - vendor/bin/sscoredump
      - vendor/etc/init/init.sscoredump.rc
      # we dont ship exo
      - system_ext/etc/default-permissions/default-exo-permissions.xml
    suffix:
      # Precompiled content
      - .art
      - .odex
      - .prof
      - .vdex
      # Sound files
      - .ogg

    prefix:
      - system/apex/
      - system_ext/apex/
      # Root CAs
      - system/etc/security/cacerts/
      - product/app/CalculatorGooglePrebuilt/
      - product/app/CalendarGooglePrebuilt/
      - product/app/Chrome-Stub/
      - product/app/Chrome/
      - product/app/DevicePolicyPrebuilt/
      # com.qualcomm.qti.devicestatisticsservice found on 5th gen Pixels
      - product/app/DeviceStatisticsService/
      # com.google.android.apps.diagnosticstool
      - product/app/DiagnosticsToolPrebuilt/
      - product/app/Drive/
      - product/app/GoogleCamera/
      - product/app/GoogleContacts/
      - product/app/GoogleContactsSyncAdapter/
      - product/app/GoogleTTS/
      # Gboard
      - product/app/HealthConnectHideApps/
      - product/app/LatinIMEGooglePrebuilt
      - product/app/LocationHistoryPrebuilt/
      - product/app/Maps/
      # com.google.android.markup is a screenshot/image editor
      - product/app/MarkupGoogle/
      - product/app/MicropaperPrebuilt/
      - product/app/ModuleMetadataGoogle/
      - product/app/MotionSenseBridgePrebuilt/
      # NexusWallpapersStubPrebuilt{2019,2020_midyear}
      - product/app/NexusWallpapers
      # NGA is "Next generation Assistant"
      - product/app/NgaResources/
      # com.google.vr.apps.ornament, found on 4th gen Pixels
      - product/app/Ornament/
      - product/app/Photos/
      # PixelCameraServices{B3,P10,Oriole,Raven,Sunfish} etc
      - product/app/PixelCameraServices
      # PixelThemesStub{,2022_and_newer}
      - product/app/PixelThemesStub
      # PixelWallpapers{2021,2021a,2022}
      - product/app/PixelWallpapers
      - product/app/PlayAutoInstallConfig/
      - product/app/PlayBooksPrebuilt/
      - product/app/PrebuiltDeskClockGoogle/
      - product/app/PrebuiltGmail/
      - product/app/PrebuiltGoogleAdservicesTvp/
      - product/app/PrebuiltGoogleTelemetryTvp/
      - product/app/SSRestartDetector/
      - product/app/SafetyHubHideApps/
      - product/app/SafetyRegulatoryInfo/
      # com.google.android.accessibility.soundamplifier
      - product/app/SoundAmplifierPrebuilt/
      - product/app/SoundPickerPrebuilt/
      - product/app/TrichromeLibrary/
      - product/app/TrichromeLibrary-Stub/
      # Google Fi app, com.google.android.apps.tycho
      - product/app/Tycho/
      - product/app/VZWAPNLib/
      # Google TV app, com.google.android.videos
      - product/app/Videos/
      # com.google.android.apps.accessibility.voiceaccess
      - product/app/VoiceAccessPrebuilt/
      # WallpapersBReel{2019,2020,2020aBramble etc}, WallpaperEmojiPrebuilt etc
      - product/app/Wallpaper
      - product/app/WebViewGoogle/
      - product/app/WebViewGoogle-Stub/
      - product/app/YouTube
      # "Google Play Services for AR", com.google.ar.core
      - product/app/arcore/
      - product/app/talkback/
      - product/priv-app/AdaptiveVPNPrebuilt/
      # "Pixel Ambient Services", com.google.intelligence.sense, found on 4th and 5th gen
      - product/priv-app/AmbientSensePrebuilt/
      # "Cross-Device Services", com.google.ambient.streaming, used for integration with ChromeOS
      - product/priv-app/AmbientStreaming/
      - product/priv-app/AndroidAutoStubPrebuilt/
      - product/priv-app/AndroidMediaShell/
      # com.verizon.services
      - product/priv-app/AppDirectedSMSService/
      - product/priv-app/BetaFeedback/
      - product/priv-app/BetterBug/
      - product/priv-app/BetterBugStub/
      - product/priv-app/CarrierLocation/
      - product/priv-app/CarrierMetrics/
      - product/priv-app/CarrierServices/
      - product/priv-app/CarrierSettings/
      - product/priv-app/CarrierWifi/
      - product/priv-app/CastAuthPrebuilt/
      # com.google.android.apps.cbrsnetworkmonitor
      - product/priv-app/CbrsNetworkMonitor/
      # com.google.android.configupdater
      - product/priv-app/ConfigUpdater/
      - product/priv-app/ConnMO/
      # com.android.sdm.plugins.dcmo, "Carrier OMA Device Management"
      - product/priv-app/DCMO/
      - product/priv-app/DMService/
      # "Private Compute Services", https://play.google.com/store/apps/details?id=com.google.android.as.oss
      - product/priv-app/DeviceIntelligenceNetworkPrebuilt/
      # DevicePersonalizationPrebuiltPixel{4,2021,2022}
      - product/priv-app/DevicePersonalizationPrebuiltPixel
      # com.android.sdm.plugins.diagmon, but included on Tensor Pixels too
      - product/priv-app/DiagMon/
      - product/priv-app/DiagnosticsToolPrebuilt/
      # DreamlinerPrebuilt is the Pixel Stand app, DreamlinerUpdater is firmware updater for Pixel Stand
      - product/priv-app/Dreamliner
      - product/priv-app/FilesPrebuilt/
      # "Google Connectivity Services", https://play.google.com/store/apps/details?id=com.google.android.apps.gcs
      - product/priv-app/GCS/
      - product/priv-app/GoogleCamera/
      - product/priv-app/GoogleDialer/
      - product/priv-app/GoogleHomePrebuilt/
      # com.google.android.onetimeinitializer, runs once each time OS build ID changes
      - product/priv-app/GoogleOneTimeInitializer/
      - product/priv-app/GoogleRestorePrebuilt/
      # com.google.android.hardwareinfo collects detailed info about hardware components and their health and uploads
      # them to Google. Runs each time device finishes booting.
      - product/priv-app/HardwareInfo/
      - product/priv-app/HealthConnectPrebuilt/
      # "Google Support Services", https://play.google.com/store/apps/details?id=com.google.android.apps.helprtc
      - product/priv-app/HelpRtcPrebuilt/
      # HotwordEnrollment{OKGoogleFUSION,OKGoogleHEMIDELTA,XGoogleFUSION etc}
      - product/priv-app/HotwordEnrollment
      - product/priv-app/KidsHomePrebuilt/
      - product/priv-app/KidsSupervisionStub/
      # "Google Pixel Buds" app, com.google.android.apps.wearables.maestro.companion
      - product/priv-app/MaestroPrebuilt/
      - product/priv-app/OTAConfigNoZeroTouchPrebuilt/
      # "Google Play Protect Service", https://play.google.com/store/apps/details?id=com.google.android.odad
      - product/priv-app/OdadPrebuilt/
      - product/priv-app/OemDmTrigger/
      - product/priv-app/PartnerSetupPrebuilt/
      # Play Store app (com.android.vending)
      - product/priv-app/Phonesky/
      - product/priv-app/PixelLiveWallpaperPrebuilt/
      # "Messages by Google", com.google.android.apps.messaging
      - product/priv-app/PrebuiltBugle/
      - product/priv-app/PrebuiltGmsCore/
      - product/priv-app/RecorderPrebuilt/
      - product/priv-app/RetailDemoGooglePrebuilt/
      # com.google.android.apps.scone is "Adaptive Connectivity Services", see https://support.google.com/product-documentation/answer/12321563
      - product/priv-app/SCONE/
      - product/priv-app/SSRestartDetector/
      - product/priv-app/SafetyHubPrebuilt/
      # "Live Transcribe & Notification", com.google.audio.hearing.visualization.accessibility.scribe
      - product/priv-app/ScribePrebuilt/
      # https://play.google.com/store/apps/details?id=com.google.android.apps.security.securityhub
      - product/priv-app/SecurityHubPrebuilt/
      # https://play.google.com/store/apps/details?id=com.google.android.settings.intelligence
      - product/priv-app/SettingsIntelligenceGooglePrebuilt/
      - product/priv-app/SetupWizardPrebuilt/
      # com.customermobile.preload.vzw, found on 6th and 7th gen Pixels
      - product/priv-app/Showcase/
      - product/priv-app/SmartDisplayPrebuilt/
      # com.android.sdm.plugins.sprintdm
      - product/priv-app/SprintDM/
      - product/priv-app/SprintHM/
      # com.google.android.tetheringentitlement
      - product/priv-app/TetheringEntitlement/
      # Pixel Tips, com.google.android.apps.tips
      - product/priv-app/TipsPrebuilt/
      # Device Health Services, https://play.google.com/store/apps/details?id=com.google.android.apps.turbo
      - product/priv-app/TurboPrebuilt/
      # com.android.sdm.plugins.usccdm
      - product/priv-app/USCCDM/
      # Google search app (GSA), com.google.android.googlequicksearchbox
      - product/priv-app/Velvet/
      - product/priv-app/WallpaperEffect/
      # Digital Wellbeing, https://play.google.com/store/apps/details?id=com.google.android.apps.wellbeing
      - product/priv-app/WellbeingPrebuilt/
      # Wi-Fi Calling setup, com.google.android.apps.wfcactivation
      - product/priv-app/WfcActivation/
      - system/app/BluetoothMigrationForBeta3User/
      - system/app/CaptivePortalLoginGoogle/
      - system/app/GoogleBluetoothLegacyMigration/
      - system/app/GoogleExtShared/
      - system/app/GooglePrintRecommendationService/
      - system/priv-app/DocumentsUIGoogle/
      - system/priv-app/GooglePackageInstaller/
      - system/priv-app/NetworkPermissionConfigGoogle/
      - system/priv-app/NetworkStackGoogle/
      - system/priv-app/TagGoogle/
      - system_ext/app/EmergencyInfoGoogleNoUi/
      # "Extreme Battery Saver", com.google.android.flipendo
      - system_ext/app/Flipendo/
      - system_ext/priv-app/CarrierSetup/
      # Manages thermal throttling of cellular and Wi-Fi connectivity, com.google.android.connectivitythermalpowermanager
      - system_ext/priv-app/ConnectivityThermalPowerManager/
      - system_ext/priv-app/DockManagerPrebuilt/
      - system_ext/priv-app/DockSetup/
      - system_ext/priv-app/FactoryOtaPrebuilt/
      - system_ext/priv-app/GoogleFeedback/
      - system_ext/priv-app/GoogleServicesFramework/
      # High Brightness Mode manager
      - system_ext/priv-app/HbmSVManager/
      # com.verizon.llkagent provides StoreDemoModeService
      - system_ext/priv-app/LLKAgent/
      - system_ext/priv-app/MyVerizonServices/
      - system_ext/priv-app/NexusLauncherRelease/
      - system_ext/priv-app/OBDM_Permissions/
      # "Motion Sense" app on 4th gen Pixels, com.google.oslo
      - system_ext/priv-app/OsloFeedback/
      - system_ext/priv-app/PixelSetupWizard/
      - system_ext/priv-app/QuickAccessWallet/
      - system_ext/priv-app/RilConfigService/
      - system_ext/priv-app/SettingsGoogle/
      - system_ext/priv-app/SettingsGoogleFutureFaceEnroll/
      - system_ext/priv-app/StorageManagerGoogle/
      - system_ext/priv-app/SystemUIGoogle/
      # Pixel Tablet
      - system_ext/priv-app/SystemUITitan/
      # com.google.android.turboadapter, see TurboPrebuilt above
      - system_ext/priv-app/TurboAdapter/
      # com.google.android.uvexposurereporter talks to the uv_exposure context hub nanoapp
      - system_ext/priv-app/UvExposureReporter/
      - system_ext/priv-app/WallpaperPickerGoogleRelease/
      # Shows disclaimer screen on beta builds
      - system_ext/priv-app/YadaYada/
      - system_ext/priv-app/grilservice/
      # com.verizon.obdm
      - system_ext/priv-app/obdm_stub/
      # Fonts
      - product/fonts/
      - system/fonts/
      - system_ext/fonts/
      - vendor/fonts/
      # Irrelevant AVB keys
      - product/etc/security/avb/
      # Irrelevant Google Assistant stuff // on-device AI
      - product/etc/ambient/
      # there's music_detector.{descriptor,sound_model,sound_model_2}
      - product/etc/firmware/music_detector
      - product/usr/srec/
      # Irrelevant Google keyboard localization
      - product/usr/share/ime/google/d3_lms/
      # Irrelevant wallpaper stuff
      - product/wallpaper/image/
      # Kernel modules
      - odm/lib/modules/
      - odm_dlkm/
      - vendor/lib/modules/
      - vendor_dlkm/
      # Overlay apps
      - product/overlay/
      - system/overlay/
      - system_ext/overlay/
      - vendor/overlay/
      # used to make proprietary Google apps default handlers of various intents
      - product/etc/preferred-apps/
      # fs-verity certificates for GmsCore and Play Store
      - product/etc/security/fsverity/
