platform:
  sepolicy_dirs:
    - device/google/gs201-sepolicy

includes:
  - pixel.yml

filters:
  dep_files:
    match:
      # external/android-nn-driver/Android.mk: error: "android.hardware.neuralnetworks@1.0-service-armnn (EXECUTABLES android-arm64) missing libOpenCL (SHARED_LIBRARIES android-arm64)"
      - vendor/lib/libOpenCL.so
      - vendor/lib64/libOpenCL.so
      - vendor/lib/egl/libGLES_mali.so
      - vendor/lib64/egl/libGLES_mali.so
