filters:
  overlay_files:
    prefix:
      - DockSetup_
      # these overlays are for packages that are not shipped
      - Flipendo
      - GoogleDeviceLockControllerOverlay
      - GoogleHealthConnectOverlay
      - HbmSVManager__auto_generated_rro_
      - PixelSetupWizardOverlay
      - Scone
      - TipsOverlay

  overlay_keys:
    prefix:
      # Face Unlock
      - com.google.android.settings.future.biometrics.faceenroll
      # Fonts
      - android:string/config_bodyFont
      - android:string/config_headlineFont
      # Help and Feedback
      - android:string/config_feedbackIntent
      - android:string/config_helpIntent
      - android:string/config_helpPackage
      # "Face unlock" is not shipped
      - com.android.settings:bool/config_face_
      - com.android.settings:string/config_face_
      - com.android.settings:string/security_settings_face_
      # Pixel SetupWizard
      - com.google.android.pixel.setupwizard
      # Unused
      - com.google.android.cellbroadcastreceiver/CellBroadcastCustomization
      - com.google.android.cellbroadcastservice/CellBroadcastServiceCustomization
      - com.google.android.documentsui/DocumentsUICustomization
      # Unused SIM app stuff
      - com.android.simappdialog
      # Unwanted Permissions link
      - com.android.permissioncontroller
      # Unwanted icons
      - android:drawable/ic_doc_
      # Useless defaults
      - com.android.providers.settings
      # Useless provisioning items
      - com.android.managedprovisioning
      - com.android.systemui:string/config_dock_setup_
      # google media apexs
      - com.google.android.providers.media.module
      - com.google.android.storagemanager
      - com.google.android.apps.nexuslauncher
      # unused oma-dm stuff
      - com.android.omadm.service
    substring:
      - branded_vpn
      # "Face unlock" is not shipped
      - /config_face_
      - /face_acquired
    match:
      - android:bool/config_pauseWallpaperRenderWhenStateChangeEnabled
      - android:bool/config_adaptive_sleep_available
      - android:bool/config_assistLongPressHomeEnabledDefault
      - android:bool/config_assistTouchGestureEnabledDefault
      - android:bool/config_bugReportHandlerEnabled
      - android:bool/config_defaultRingtonePickerEnabled
      - android:bool/config_enableFusedLocationOverlay
      - android:bool/config_enableGeocoderOverlay
      - android:bool/config_enableGeofenceOverlay
      - android:bool/config_enableGeolocationTimeZoneDetection
      - android:bool/config_enableNetworkLocationOverlay
      - android:bool/config_enablePrimaryLocationTimeZoneProvider
      - android:bool/config_enableSecondaryLocationTimeZoneProvider
      - android:bool/config_pinnerCameraApp
      - android:bool/config_pinnerHomeApp
      - android:bool/config_profcollectReportUploaderEnabled
      - android:bool/config_sendPackageName
      - android:bool/config_showGesturalNavigationHints
      - android:bool/config_smart_battery_available
      - android:bool/config_volumeAdjustmentForRemoteGroupSessions
      - android:bool/config_volumeHushGestureEnabled
      - android:drawable/ic_safety_protection
      - android:integer/config_defaultNightMode
      - android:integer/config_keyChordPowerVolumeUp
      - android:integer/config_longPressOnPowerBehavior
      - android:integer/config_multiuserMaximumUsers
      - android:integer/config_pinnerWebviewPinBytes
      - android:integer/config_storageManagerDaystoRetainDefault
      - android:string-array/config_accessibility_allowed_install_source
      - android:string-array/config_allowedSecureInstantAppSettings
      - android:string-array/config_batteryPackageTypeService
      - android:string-array/config_companionDeviceCerts
      - android:string-array/config_companionDevicePackages
      - android:string-array/config_companionDevicePackages
      - android:string-array/config_defaultCloudSearchServices
      - android:string-array/config_defaultFirstUserRestrictions
      - android:string-array/config_disabledUntilUsedPreinstalledImes
      - android:string-array/config_disabledUntilUsedPreinstalledImes
      # com.google.android.gms/.auth.api.credentials.credman.service.PasswordAndPasskeyService
      - android:string-array/config_enabledCredentialProviderService
      - android:string-array/config_ephemeralResolverPackage
      # /product/etc/security/fsverity/gms_fsverity_cert.der
      - android:string-array/config_fontManagerServiceCerts
      - android:string-array/config_forceQueryablePackages
      # B2C0A80E485934BFB08F902CA27505813DF3159E4E6DD4A4DF078D66CB1C2003
      - android:string-array/config_healthConnectMigrationKnownSigners
      # 56BE132B780656FE2444CD34326EB5D7AAC91D2096ABF0FE673A99270622EC87
      - android:string-array/config_healthConnectRestoreKnownSigners
      - android:string-array/config_integrityRuleProviderPackages
      - android:string-array/config_keep_warming_services
      - android:string-array/config_locationExtraPackageNames
      - android:string-array/config_locationProviderPackageNames
      - android:string-array/config_loggable_dream_prefixes
      - android:string-array/config_nonBlockableNotificationPackages
      - android:string-array/config_nonBlockableNotificationPackages
      - android:string-array/config_packagesExemptFromSuspension
      # com.google.android.gms/.auth.api.credentials.credman.service.PasswordAndPasskeyService
      - android:string-array/config_primaryCredentialProviderService
      - android:string-array/config_priorityOnlyDndExemptPackages
      - android:string-array/config_priorityOnlyDndExemptPackages
      # first appeared in Pixel Fold 14 QPR1 image
      - android:string-array/default_wallpaper_component_per_device_color
      # set to Google Camera
      - android:string-array/pause_wallpaper_render_when_state_change
      - android:string-array/vendor_cross_profile_apps
      - android:string-array/vendor_cross_profile_apps
      - android:string-array/vendor_disallowed_apps_managed_device
      - android:string-array/vendor_disallowed_apps_managed_profile
      - android:string-array/vendor_disallowed_apps_managed_user
      - android:string-array/vendor_required_apps_managed_device
      - android:string-array/vendor_required_apps_managed_profile
      - android:string-array/vendor_required_apps_managed_user
      - android:string/config_appsAuthorizedForSharedAccounts
      - android:string/config_batterySaverScheduleProvider
      - android:string/config_defaultAccessibilityService
      - android:string/config_defaultAmbientContextConsentComponent
      - android:string/config_defaultAmbientContextDetectionService
      - android:string/config_defaultAppPredictionService
      - android:string/config_defaultAssistant
      - android:string/config_defaultAssistantAccessComponent
      - android:string/config_defaultAttentionService
      - android:string/config_defaultAugmentedAutofillService
      - android:string/config_defaultAutofillService
      - android:string/config_defaultBugReportHandlerApp
      - android:string/config_defaultCaptivePortalLoginPackageName
      - android:string/config_defaultContentCaptureService
      - android:string/config_defaultContentProtectionService
      - android:string/config_defaultContentSuggestionsService
      # com.google.android.gms/.auth.api.credentials.credman.service.RemoteService
      - android:string/config_defaultCredentialManagerHybridService
      - android:string/config_defaultDialer
      - android:string/config_defaultDndAccessPackages
      - android:string/config_defaultDockManagerPackageName
      # com.google.android.as/com.google.android.apps.miphone.aiai.app.AutofillFieldClassificationService
      - android:string/config_defaultFieldClassificationService
      - android:string/config_defaultGallery
      - android:string/config_defaultListenerAccessPackages
      - android:string/config_defaultModuleMetadataProvider
      - android:string/config_defaultMusic
      - android:string/config_defaultMusicRecognitionService
      - android:string/config_defaultNearbyFastPairSettingsDevicesComponent
      - android:string/config_defaultNearbySharingComponent
      - android:string/config_defaultNetworkRecommendationProviderPackage
      # com.google.android.keep
      - android:string/config_defaultNotes
      - android:string/config_defaultOnDeviceSpeechRecognitionService
      - android:string/config_defaultProfcollectReportUploaderAction
      - android:string/config_defaultProfcollectReportUploaderApp
      - android:string/config_defaultQrCodeComponent
      - android:string/config_defaultRetailDemo
      - android:string/config_defaultRotationResolverService
      - android:string/config_defaultSearchSelectorPackageName
      - android:string/config_defaultSearchUiService
      - android:string/config_defaultSmartspaceService
      - android:string/config_defaultSms
      - android:string/config_defaultSupervisionProfileOwnerComponent
      - android:string/config_defaultSystemCaptionsManagerService
      - android:string/config_defaultSystemCaptionsService
      - android:string/config_defaultTextClassifierPackage
      - android:string/config_defaultTranslationService
      - android:string/config_defaultWallpaperEffectsGenerationService
      - android:string/config_defaultWellbeingPackage
      - android:string/config_deviceConfiguratorPackageName
      - android:string/config_devicePolicyManagement
      - android:string/config_devicePolicyManagementUpdater
      - android:string/config_deviceProvisioningPackage
      - android:string/config_dreamsDefaultComponent
      - android:string/config_emergency_dialer_package
      # com.google.android.apps.healthdata
      - android:string/config_healthConnectMigratorPackageName
      - android:string/config_helpPackageNameValue
      - android:string/config_incidentReportApproverPackage
      - android:string/config_loggable_dream_prefix
      - android:string/config_persistentDataPackageName
      - android:string/config_powerSaveModeChangedListenerPackage
      - android:string/config_primaryLocationTimeZoneProviderPackageName
      - android:string/config_recentsComponentName
      - android:string/config_retailDemoPackage
      - android:string/config_retailDemoPackageSignature
      - android:string/config_secondaryHomePackage
      - android:string/config_secondaryLocationTimeZoneProviderPackageName
      - android:string/config_servicesExtensionPackage
      - android:string/config_sharedConnectivityServiceIntentAction
      - android:string/config_sharedConnectivityServicePackage
      # set to Play services on tangorpro
      - android:string/config_supervisedUserCreationPackage
      - android:string/config_systemActivityRecognizer
      - android:string/config_systemAmbientAudioIntelligence
      - android:string/config_systemAppProtectionService
      - android:string/config_systemAudioIntelligence
      - android:string/config_systemAutomotiveProjection
      - android:string/config_systemBluetoothStack
      # com.google.android.gms
      - android:string/config_systemCallStreaming
      - android:string/config_systemCompanionDeviceProvider
      - android:string/config_systemContacts
      # com.google.android.devicelockcontroller
      - android:string/config_systemFinancedDeviceController
      - android:string/config_systemGallery
      - android:string/config_systemGameService
      - android:string/config_systemImageEditor
      - android:string/config_systemNotificationIntelligence
      - android:string/config_systemSettingsIntelligence
      - android:string/config_systemSpeechRecognizer
      - android:string/config_systemSupervision
      - android:string/config_systemTextIntelligence
      - android:string/config_systemUiIntelligence
      - android:string/config_systemVisualIntelligence
      - android:string/config_systemWellbeing
      - android:string/config_wallpaperCropperPackage
      - android:string/default_wallpaper_component
      - android:string/harmful_app_warning_title
      - android:string/widget_default_class_name
      - android:string/widget_default_package_name
      - com.android.networkstack/NetworkStackConfig:bool/config_dhcp_client_hostname
      - com.android.phone:string-array/thermal_mitigation_allowlisted_packages
      - com.android.phone:string/dialer_default_class
      - com.android.phone:string/platform_carrier_config_package
      - com.android.phone:string/platform_number_verification_package
      - com.android.providers.contacts:string/metadata_sync_pacakge
      - com.android.providers.telephony:string/apn_source_service
      - com.android.server.telecom:string/call_diagnostic_service_package_name
      - com.android.server.telecom:string/dialer_default_class
      - com.android.settings:bool/config_auto_rotate_face_detection_available
      - com.android.settings:bool/config_nfc_detection_point
      - com.android.settings:bool/config_show_communal_settings
      - com.android.settings:bool/config_show_reverse_charging
      - com.android.settings:bool/config_show_touch_sensitivity
      - com.android.settings:bool/config_suc_use_partner_resource
      - com.android.settings:bool/config_suw_support_face_enroll
      - com.android.settings:drawable/$aware_assist_static__0
      - com.android.settings:drawable/$aware_assist_static__1
      - com.android.settings:drawable/aware_assist_static
      - com.android.settings:integer-array/datausage_hiding_carrier_service_carrier_id
      - com.android.settings:integer-array/face_enroll_primary_buckets
      - com.android.settings:string-array/config_preinstalled_dream_components
      - com.android.settings:string-array/config_settings_slices_accessibility_components
      - com.android.settings:string-array/datausage_hiding_carrier_service_package_names
      - com.android.settings:string-array/slice_allowlist_package_names
      # "Google Assistant"
      - com.android.systemui.accessibility.accessibilitymenu:string/assistant_utterance
      - com.android.systemui:bool/config_touch_context_enabled
      - com.android.systemui:bool/config_wlc_support_enabled
      - com.android.systemui:integer/config_keyguardRefreshRate
      - com.android.systemui:string-array/config_communalWidgetAllowlist
      - com.android.systemui:string-array/config_controlsPreferredPackages
      - com.android.systemui:string-array/config_dock_setup_completed_packages
      # first appeared in Pixel Tablet 14 QPR1 image, set to com.google.android.apps.mediashell
      - com.android.systemui:string-array/config_fingerprint_listen_on_occluding_activity_packages
      - com.android.systemui:string-array/config_pluginWhitelist
      - com.android.systemui:string/branded_monitoring_description_app_personal
      - com.android.systemui:string/config_cameraProtectionExcludedPackages
      - com.android.systemui:string/config_communalSourceComponent
      - com.android.systemui:string/config_communalSourceConnector
      - com.android.systemui:string/config_media_shell_service_component
      - com.android.systemui:string/config_nest_dock_manager_service_component
      - com.android.systemui:string/config_dockComponent
      - com.android.systemui:string/config_remoteCopyPackage
      # set to Google Files app, "sceenshot" typo is upstream
      - com.android.systemui:string/config_sceenshotWorkProfileFilesApp
      - com.android.systemui:string/config_screenshotEditor
      - com.android.systemui:string/quick_settings_tiles_default
      - com.android.systemui:string/config_lowLightDreamComponent
      # Config not copied from Google's SystemUI, to disallow overriding it
      - com.android.systemui:bool/custom_lockscreen_shortcuts_enabled
